# Generated by Buildr 1.3.5, change to your liking
# Version number for this release
require 'buildr/scala'
ENV['SCALA_HOME'] = '/opt/scala'
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "cert-generation"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"
BOUNCYCASTLE = group('bcprov-jdk16', 'bcpg-jdk16', :under=>'org.bouncycastle', :version=>'1.44')

desc "The Cert-generation project"
define "cert-generation" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  resources
  test.resources
  compile.with BOUNCYCASTLE
  package :jar
  task :run => :compile do
    system 'java -cp target/classes'+ compile.dependencies.map(&:name).join(File::PATH_SEPARATOR) + 'com.redhat.certgen.Main'
  end
end
